//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayloadUtils
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;

    public partial class Cbpmsadeliveryconfpayload
    {
        [ScriptIgnore]
        public int CbpmsadeliveryconfpayloadID { get; set; }
        public string customerUniqueId { get; set; }
        public string marketerReceiptNumber { get; set; }
        public string originalMarketerReceiptNumber { get; set; }
        public string orderNumber { get; set; }
        public string lineNumber { get; set; }
        public string marketerAccountNumber { get; set; }
        public string customerAccountNumber { get; set; }
        public string orderDate { get; set; }
        public string deliveryDate { get; set; }
        public string transactionType { get; set; }
        public string poNumber { get; set; }
        public string releaseNumber { get; set; }
        public string productCode { get; set; }
        public string packageCode { get; set; }
        public string numberOrdered { get; set; }
        public string deliveredQuantity { get; set; }
        public string requisitionNumber { get; set; }
        public string jobNumber { get; set; }
        public string unitNumber { get; set; }
        public string corporatePurchaseOrderID { get; set; }
        public string blanketPurchaseOrder { get; set; }
        public string automaticSendIndicator { get; set; }
        public string drumToteToBulkIndicator { get; set; }
        public string serviceFees { get; set; }
        public string partialDelivery { get; set; }
        [ScriptIgnore]
        public bool Uploaded { get; set; }
    }
}
