//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PayloadUtils;

namespace OAuth2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;
    public partial class ChevronEntities : DbContext
    {
        public ChevronEntities()
            : base("name=ChevronEntities")
        {
        }
        public ChevronEntities(string connectionString): base(connectionString)
        {

            //     this.Configuration.ValidateOnSaveEnabled = true;
            //      this.Configuration.LazyLoadingEnabled = true;
            //      this.Configuration.AutoDetectChangesEnabled = true;
  
            //Build an Entity Framework connection string

           

        }
     
       protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }


        public virtual DbSet<Cbpmsadeliveryconfpayload> Cbpmsadeliveryconfpayloads { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
    }
}
