//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuth2
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;

    public partial class Claim
    {
        [ScriptIgnore]
        public int claimsId { get; set; }
        public string deliveryDate { get; set; }
        public Nullable<decimal> rebateRate { get; set; }
        public string productCode { get; set; }
        public string c2RebateAccountNumber { get; set; }
        public Nullable<decimal> deliveredQuantity { get; set; }
        public string customerAccountName { get; set; }
        public string marketerEmail { get; set; }
        public string marketerRebateNumber { get; set; }
        public string clientId { get; set; }
        public string customerAccountNumber { get; set; }
        public string packageCode { get; set; }
        public string marketerName { get; set; }
        [ScriptIgnore]
        public bool Uploaded { get; set; }
    }
}
