//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="MEF_Test_Interface")]
public interface MEF_Test_Interface
{
    
    [System.ServiceModel.OperationContractAttribute(Action="SubmissionListByTransmissionId", ReplyAction="http://tempuri.org/MEF_Test_Interface/SubmissionListByTransmissionIdResponse")]
    object SubmissionListByTransmissionId(string UserName, string Password, string TransmissionId);
    
    [System.ServiceModel.OperationContractAttribute(Action="SubmissionListByDate", ReplyAction="http://tempuri.org/MEF_Test_Interface/SubmissionListByDateResponse")]
    object SubmissionListByDate(string UserName, string Password, string DateFrom, string DateTo);
    
    [System.ServiceModel.OperationContractAttribute(Action="NewSubmission", ReplyAction="http://tempuri.org/MEF_Test_Interface/NewSubmissionResponse")]
    object NewSubmission(string UserName, string Password, object File);
    
    [System.ServiceModel.OperationContractAttribute(Action="SubmissionListByAcknowledgementId", ReplyAction="http://tempuri.org/MEF_Test_Interface/SubmissionListByAcknowledgementIdResponse")]
    object SubmissionListByAcknowledgementId(string UserName, string Password, string AcknowledgementId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface MEF_Test_InterfaceChannel : MEF_Test_Interface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MEF_Test_InterfaceClient : System.ServiceModel.ClientBase<MEF_Test_Interface>, MEF_Test_Interface
{
    
    public MEF_Test_InterfaceClient()
    {
    }
    
    public MEF_Test_InterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MEF_Test_InterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MEF_Test_InterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MEF_Test_InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public object SubmissionListByTransmissionId(string UserName, string Password, string TransmissionId)
    {
        return base.Channel.SubmissionListByTransmissionId(UserName, Password, TransmissionId);
    }
    
    public object SubmissionListByDate(string UserName, string Password, string DateFrom, string DateTo)
    {
        return base.Channel.SubmissionListByDate(UserName, Password, DateFrom, DateTo);
    }
    
    public object NewSubmission(string UserName, string Password, object File)
    {
        return base.Channel.NewSubmission(UserName, Password, File);
    }
    
    public object SubmissionListByAcknowledgementId(string UserName, string Password, string AcknowledgementId)
    {
        return base.Channel.SubmissionListByAcknowledgementId(UserName, Password, AcknowledgementId);
    }
}
