//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="MFET_Interface")]
public interface MFET_Interface
{
    
    [System.ServiceModel.OperationContractAttribute(Action="SubmissionListByAcknowledgementId", ReplyAction="http://tempuri.org/MFET_Interface/SubmissionListByAcknowledgementIdResponse")]
    object SubmissionListByAcknowledgementId(string UserName, string Password, string AcknowledgementId);
    
    [System.ServiceModel.OperationContractAttribute(Action="SubmissionListByDate", ReplyAction="http://tempuri.org/MFET_Interface/SubmissionListByDateResponse")]
    object SubmissionListByDate(string UserName, string Password, string DateFrom, string DateTo);
    
    [System.ServiceModel.OperationContractAttribute(Action="SubmissionListByTransmissionId", ReplyAction="http://tempuri.org/MFET_Interface/SubmissionListByTransmissionIdResponse")]
    object SubmissionListByTransmissionId(string UserName, string Password, string TransmissionId);
    
    [System.ServiceModel.OperationContractAttribute(Action="NewSubmission", ReplyAction="http://tempuri.org/MFET_Interface/NewSubmissionResponse")]
    object NewSubmission(string UserName, string Password, object File);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface MFET_InterfaceChannel : MFET_Interface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MFET_InterfaceClient : System.ServiceModel.ClientBase<MFET_Interface>, MFET_Interface
{
    
    public MFET_InterfaceClient()
    {
    }
    
    public MFET_InterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MFET_InterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MFET_InterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MFET_InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public object SubmissionListByAcknowledgementId(string UserName, string Password, string AcknowledgementId)
    {
        return base.Channel.SubmissionListByAcknowledgementId(UserName, Password, AcknowledgementId);
    }
    
    public object SubmissionListByDate(string UserName, string Password, string DateFrom, string DateTo)
    {
        return base.Channel.SubmissionListByDate(UserName, Password, DateFrom, DateTo);
    }
    
    public object SubmissionListByTransmissionId(string UserName, string Password, string TransmissionId)
    {
        return base.Channel.SubmissionListByTransmissionId(UserName, Password, TransmissionId);
    }
    
    public object NewSubmission(string UserName, string Password, object File)
    {
        return base.Channel.NewSubmission(UserName, Password, File);
    }
}
